# Generated by Django 5.1.7 on 2025-03-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=100)),
                ('loan_type', models.CharField(max_length=50)),
                ('borrower', models.CharField(max_length=100)),
                ('borrower_address', models.TextField()),
                ('co_borrower', models.CharField(blank=True, max_length=100, null=True)),
                ('co_borrower_address', models.TextField(blank=True, null=True)),
                ('current_dpd', models.IntegerField()),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('region', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=10)),
            ],
        ),
    ]
